all: tcp_client.c tcp_server.c
	gcc -g -Wall -o tcp_client tcp_client.c
	gcc -g -Wall -o tcp_client2 tcp_client2.c
	gcc -g -Wall -o tcp_server tcp_server.c

run:
	@echo "run"

test:
	@echo "test"

clean:
	rm -rf *.o tcp_client tcp_client2 tcp_server
